#
# (C) Copyright 2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_BITBANGMII) += miiphybb.o
obj-$(CONFIG_MV88E61XX_SWITCH) += mv88e61xx.o
obj-$(CONFIG_MV88E6352_SWITCH) += mv88e6352.o
obj-$(CONFIG_QCA8K_SWITCH) += qca8k.o
obj-$(CONFIG_RTL83XX_SWITCH) += rtl83xx/rtk_switch.o rtl83xx/rtl8367c_asicdrv.o \
						rtl83xx/rtl8367c_asicdrv_phy.o rtl83xx/rtl8367c_asicdrv_inbwctrl.o \
						rtl83xx/rtl8367c_asicdrv_scheduling.o rtl83xx/rtl8367c_asicdrv_lut.o \
						rtl83xx/rtl8367c_asicdrv_rma.o rtl83xx/rtl8367c_asicdrv_mirror.o \
						rtl83xx/smi.o rtl83xx/port.o rtl83xx/rtl8367c_asicdrv_port.o \
						rtl83xx/cpu.o rtl83xx/rtl8367c_asicdrv_cputag.o rtl83xx/stat.o rtl83xx/rtl8367c_asicdrv_mib.o \
                        rtl83xx/rtl8367c_asicdrv_led.o rtl83xx/led.o

obj-$(CONFIG_PHYLIB) += phy.o
obj-$(CONFIG_PHYLIB_10G) += generic_10g.o
obj-$(CONFIG_PHY_AQUANTIA) += aquantia.o
obj-$(CONFIG_PHY_ATHEROS) += atheros.o
obj-$(CONFIG_PHY_BROADCOM) += broadcom.o
obj-$(CONFIG_PHY_CORTINA) += cortina.o
obj-$(CONFIG_PHY_DAVICOM) += davicom.o
obj-$(CONFIG_PHY_ET1011C) += et1011c.o
obj-$(CONFIG_PHY_LXT) += lxt.o
obj-$(CONFIG_PHY_MARVELL) += marvell.o
obj-$(CONFIG_PHY_MICREL) += micrel.o
obj-$(CONFIG_PHY_NATSEMI) += natsemi.o
obj-$(CONFIG_PHY_REALTEK) += realtek.o
obj-$(CONFIG_PHY_SMSC) += smsc.o
obj-$(CONFIG_PHY_TERANETICS) += teranetics.o
obj-$(CONFIG_PHY_VITESSE) += vitesse.o
